apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend
  description: An example of a Backstage application.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
  metadata:
    name: process-graph-api
    description: https://github.com/nextgovbr/process-graph-api
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
  annotations:
    backstage.io/source-template: template:default/springboot-template
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: artist-engagement-portal
  dependsOn: ['resource:artists-db']
  apiConsumedBy: ['component:www-artist']
